prueba

diff --git a/.github/workflows/aws.yml b/.github/workflows/aws.yml
--- a/.github/workflows/aws.yml
+++ b/.github/workflows/aws.yml
@@ -18,11 +18,7 @@ jobs:
 
     - name: Set up .env for dev
       if: github.ref == 'refs/heads/server-dev'
-      run: echo "NODE_ENV=${{ secrets.NODE_ENV }}\nBACKEND_SERVICE_DEV=${{ secrets.BACKEND_SERVICE_DEV }}\nCOMPOSE_PROJECT_NAME=${{ secrets.COMPOSE_PROJECT_NAME }}" > .env
-
-    - name: Set up .env for prod
-      if: github.ref == 'refs/heads/server-prod'
-      run: echo "NODE_ENV=${{ secrets.NODE_ENV }}\nBACKEND_SERVICE_PROD=${{ secrets.BACKEND_SERVICE_PROD }}\nCOMPOSE_PROJECT_NAME=${{ secrets.COMPOSE_PROJECT_NAME }}" > .env
+      run: echo "BACKEND_SERVICE=${{ secrets.BACKEND_SERVICE }}\nCOMPOSE_PROJECT_NAME=${{ secrets.COMPOSE_PROJECT_NAME }}" > .env
 
     - name: Set up Node.js
       uses: actions/setup-node@v2
@@ -135,9 +131,8 @@ jobs:
           echo "Error: el archivo .env no existe"
           exit 1
         fi
-        scp .env ubuntu@107.22.89.148:/home/ubuntu/server-prod/.env || (echo "Error al copiar el archivo .env"; exit 1)
+        scp .env ubuntu@107.22.89.148:/home/ubuntu/server-dev/.env || (echo "Error al copiar el archivo .env"; exit 1)
         ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@107.22.89.148 << 'EOF' 
-          
           mkdir -p /home/ubuntu/server-prod
           sudo usermod -aG docker $USER
           sudo chmod 666 /var/run/docker.sock
@@ -158,7 +153,8 @@ jobs:
             git pull origin server-prod || (echo "Error al actualizar el repositorio"; exit 1)
           fi
           
-          # Levantar los contenedores
+          # Levantar contenedores
+          cd /home/ubuntu/server-prod
           docker-compose down
           docker-compose up -d
         EOF
