Update aws.yml

diff --git a/.github/workflows/aws.yml b/.github/workflows/aws.yml
--- a/.github/workflows/aws.yml
+++ b/.github/workflows/aws.yml
@@ -37,51 +37,6 @@ jobs:
       with:
         node-version: '18'
 
-    # # Instalar dependencias para el backend
-    # - name: Install backend dependencies
-    #   run: npm install
-    #   working-directory: ./app/backend  # Ruta del backend
-    
-    # # Ejecutar pruebas del backend 
-    # - name: Run backend tests 
-    #   run: npm test 
-    #   working-directory: ./app/backend # Ruta del backend
-
-    # # Instalar dependencias para el frontend
-    # - name: Install frontend dependencies
-    #   run: npm install
-    #   working-directory: ./app/frontend  # Ruta del frontend
-
-    # # Instalar navegadores de Playwright
-    # - name: Install Playwright browsers
-    #   run: npx playwright install
-    #   working-directory: ./app/frontend  # Ruta del frontend
-
-    # # Iniciar el servidor frontend en segundo plano
-    # - name: Start frontend server
-    #   run: |
-    #     nohup npm start > frontend.log 2>&1 &
-    #     sleep 20  
-    #   working-directory: ./app/frontend  # Ruta del frontend
-
-    # # Ejecutar pruebas del frontend
-    # - name: Run frontend tests
-    #   run: npm test
-    #   working-directory: ./app/frontend  # Ruta del frontend
-
-    # - name: Install Docker and Docker Compose
-    #   run: |
-    #     sudo apt-get update
-    #     sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
-    #     curl -fsSL https://get.docker.com -o get-docker.sh
-    #     sudo sh get-docker.sh
-    #     sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-    #     sudo chmod +x /usr/local/bin/docker-compose
-    #     sudo systemctl enable --now docker
-
-    # - name: Build Docker image
-    #   run: docker-compose build
-
     - name: Set up SSH
       uses: webfactory/ssh-agent@v0.5.3
       with:
@@ -121,12 +76,13 @@ jobs:
           sudo chmod 666 /var/run/docker.sock
 
           if ! [ -x "$(command -v docker-compose)" ]; then
-            curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
             sudo chmod +x /usr/local/bin/docker-compose
           fi
 
           # Si el directorio no existe o no es un repositorio git, clónalo
           if [ ! -d /home/ubuntu/$BRANCH_DIR/.git ]; then
+            sudo rm -rf /home/ubuntu/$BRANCH_DIR
             git clone https://github.com/VictorCortez358/DevOps /home/ubuntu/$BRANCH_DIR
             cd /home/ubuntu/$BRANCH_DIR
             git checkout $BRANCH_DIR  # Asegúrate de usar la rama correcta
@@ -135,6 +91,11 @@ jobs:
           fi
 
           cd /home/ubuntu/$BRANCH_DIR
-          docker-compose down
-          docker-compose up -d --build
+          if [ -f docker-compose.yml ]; then
+            docker-compose down
+            docker-compose up -d --build
+          else
+            echo "docker-compose.yml not found"
+            exit 1
+          fi
         EOF
