fixed

diff --git a/.github/workflows/aws.yml b/.github/workflows/aws.yml
--- a/.github/workflows/aws.yml
+++ b/.github/workflows/aws.yml
@@ -16,10 +16,9 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v2
 
-    - name: Set up .env for dev
-      if: github.ref == 'refs/heads/server-dev'
-      run: echo "BACKEND_SERVICE=${{ secrets.BACKEND_SERVICE }}\nCOMPOSE_PROJECT_NAME=${{ secrets.COMPOSE_PROJECT_NAME }}" > .env
-
+    - name: Set up .env
+      run: |
+        echo -e "NODE_ENV=${{ secrets.NODE_ENV }}\nBACKEND_SERVICE_DEV=${{ secrets.BACKEND_SERVICE_DEV }}\nBACKEND_SERVICE_PROD=${{ secrets.BACKEND_SERVICE_PROD }}\nCOMPOSE_PROJECT_NAME=${{ secrets.COMPOSE_PROJECT_NAME }}" > .env
     - name: Set up Node.js
       uses: actions/setup-node@v2
       with:
@@ -90,7 +89,6 @@ jobs:
     - name: Add server-prod to known_hosts 
       run: | 
         ssh-keyscan -H 107.22.89.148 >> ~/.ssh/known_hosts || echo "Failed to add server-prod to known_hosts"
-
     - name: Deploy to EC2 (server-dev)
       if: github.ref == 'refs/heads/server-dev'
       run: |
@@ -99,7 +97,6 @@ jobs:
           exit 1
         fi
         scp .env ubuntu@52.207.223.222:/home/ubuntu/server-dev/.env || (echo "Error al copiar el archivo .env"; exit 1)
-
         ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@52.207.223.222 << 'EOF' 
           mkdir -p /home/ubuntu/server-dev
           sudo usermod -aG docker $USER
@@ -123,7 +120,6 @@ jobs:
           docker-compose down
           docker-compose up -d
         EOF
-
     - name: Deploy to EC2 (server-prod)
       if: github.ref == 'refs/heads/server-prod'
       run: |
@@ -133,24 +129,19 @@ jobs:
         fi
         scp .env ubuntu@107.22.89.148:/home/ubuntu/server-dev/.env || (echo "Error al copiar el archivo .env"; exit 1)
         ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@107.22.89.148 << 'EOF' 
-          mkdir -p /home/ubuntu/server-prod
+          mkdir -p /home/ubuntu/server-dev
           sudo usermod -aG docker $USER
           sudo chmod 666 /var/run/docker.sock
-
           # Instalar Docker Compose si no está presente
           if ! [ -x "$(command -v docker-compose)" ]; then
             curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
             sudo chmod +x /usr/local/bin/docker-compose
           fi
           
-          # Clonar o actualizar el repositorio
-          if [ ! -d /home/ubuntu/server-prod/.git ]; then
-            git clone https://github.com/VictorCortez358/DevOps /home/ubuntu/server-prod
-            cd /home/ubuntu/server-prod
-            git checkout server-prod
+          if [ ! -d /home/ubuntu/server-dev/.git ]; then
+            git clone https://github.com/VictorCortez358/DevOps /home/ubuntu/server-dev
           else
-            cd /home/ubuntu/server-prod
-            git pull origin server-prod || (echo "Error al actualizar el repositorio"; exit 1)
+            cd /home/ubuntu/server-dev && git pull origin server-dev || (echo "Error al actualizar el repositorio"; exit 1)
           fi
           
           # Levantar contenedores
